services:
  - type: web
    name: languella
    env: node
    plan: free
    buildCommand: cd BustlingSkeletalTruetype/project && npm install && npm run build
    startCommand: cd BustlingSkeletalTruetype/project && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false